#!/bin/bash

if [ "$1" = "debug" ]
then
	/usr/bin/php daemon.php
else
	mv logs/system/daemon logs/system/daemon.`date +%F_%k_%M_%S`
	
	nohup /usr/bin/php daemon.php > logs/system/daemon &
	
	if [ "$1" = "tail" ]
	then
		tail -f logs/system/daemon
	fi
fi
