#!/bin/bash

if [ ! -n "$2" ]
then
	echo "Usage: `basename $0` port roomID"
	exit 255
fi

if [ "$3" = "true" ]
then
	/usr/bin/php /var/www/snapchat/server/room.php $1 $2
else
	nohup /usr/bin/php /var/www/snapchat/server/room.php $1 $2 > /var/www/snapchat/server/logs/rooms/$2 &
fi

